# -*- coding: utf-8 -*-
"""Exp1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GMgoziK1pruFhtN04vHr7IMWzEOap9-g

## Exp 1: LLMs as Dectectors for 4-class Classification

## 1.1 Setup
"""

!pip install -q transformers accelerate sentencepiece scikit-learn tqdm

import random
import re
import torch
import torch.nn as nn
import torch.nn.functional as F
import numpy as np
import pandas as pd
from tqdm import tqdm
from torch.utils.data import TensorDataset, DataLoader
from sklearn.model_selection import train_test_split
from sklearn.metrics import (
    accuracy_score,
    f1_score,
    precision_score,
    recall_score,
    classification_report
)

# set seed
def set_seed(seed=42):
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    torch.cuda.manual_seed_all(seed)

set_seed(42)

# device
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print("Device:", device)

# Load Data
train_df = pd.read_csv("/content/train_dataset.csv")  # train_attack_data
test_df = pd.read_csv("/content/test_dataset.csv")

print(train_df.head())
print(test_df.head())

train_df["text"] = train_df["text"].astype(str)
test_df["text"]  = test_df["text"].astype(str)

train_df["model"] = train_df["model"].astype(str).str.lower().str.strip()
train_df["domain"] = train_df["domain"].astype(str).str.lower().str.strip()

print(train_df.loc[7624, "text"])
print(type(train_df.loc[7624, "text"]))
print(train_df.loc[7834, "text"])
print(type(train_df.loc[7834, "text"]))

train_df = train_df.drop(index=7624)
train_df = train_df.drop(index=7834)

def is_bad(x):
    if x is None:
        return True

    if isinstance(x, float) and np.isnan(x):
        return True

    s = str(x).strip().lower()

    if s == "" or s == "nan":
        return True

    return False


train_df = train_df[~train_df["text"].apply(is_bad)]

train_df, val_df = train_test_split(
    train_df,
    test_size=0.2,
    random_state=625,
    stratify=train_df["model"]
)

print("train shape:", train_df.shape)
print("val shape:", val_df.shape)
print("test shape:", test_df.shape)

print(train_df.head(8))

# Load GPT2 (more stable with float32)
# since its best performance in Exp 2b
from transformers import AutoTokenizer, AutoModelForCausalLM, AutoModelForSeq2SeqLM

gpt2_name = "gpt2-large"

gpt2 = AutoModelForCausalLM.from_pretrained(
    gpt2_name,
    torch_dtype=torch.float32
).to(device)

gpt2.eval()

gpt2_tokenizer = AutoTokenizer.from_pretrained(gpt2_name)

gpt2_tokenizer.pad_token = gpt2_tokenizer.eos_token

"""## 1.2 Features Extracted by LLM Detector"""

# Batch Tockenization
def tokenize_batch(texts, tokenizer, max_length=512):

    enc = tokenizer(
        texts,
        return_tensors="pt",
        padding=True,
        truncation=True,
        max_length=max_length
    )

    return enc

# Batch LogProb
# Padding can accelerate the computation, but it will also contaminate logprob.
# Thus, we should have attention_mask.

def get_batch_token_logprobs(model, input_ids, attention_mask):
    input_ids = input_ids.to(device)
    attention_mask = attention_mask.to(device)

    with torch.no_grad():
        outputs = model(input_ids)
        logits = outputs.logits  # [B, L, V]

    # shift for next-token prediction
    shift_logits = logits[:, :-1, :]
    shift_labels = input_ids[:, 1:]
    shift_mask   = attention_mask[:, 1:]

    log_probs = F.log_softmax(shift_logits, dim=-1)

    token_log_probs = log_probs.gather(
        2,
        shift_labels.unsqueeze(-1)
    ).squeeze(-1)

    token_log_probs = token_log_probs * shift_mask

    return token_log_probs.cpu().numpy(), shift_mask.cpu().numpy()

# Feature Engineering
def compute_features(token_log_probs, mask):

    token_log_probs = np.array(token_log_probs)
    mask = np.array(mask)

    valid = token_log_probs[mask == 1]

    if len(valid) == 0:
        return np.zeros(10)

    # basic stats
    mean_lp = valid.mean()
    std_lp = valid.std()
    min_lp = valid.min()
    max_lp = valid.max()
    median_lp = np.median(valid)
    perplexity = np.exp(-mean_lp) # perplexity

    # logrank
    ranks = np.argsort(np.argsort(-valid))
    logrank = np.mean(np.log1p(ranks + 1))
    rank_var = np.var(ranks)

    # entropy
    probs = np.exp(valid)
    probs = probs / (np.sum(probs) + 1e-12)
    entropy = -np.sum(probs * np.log(probs + 1e-12))

    # tail entropy
    k = max(1, int(0.2 * len(valid)))
    tail_probs = np.sort(probs)[:k]
    tail_probs = tail_probs / (np.sum(tail_probs) + 1e-12)
    tail_entropy = -np.sum(tail_probs * np.log(tail_probs + 1e-12))

    return np.array([
        logrank,
        mean_lp,
        std_lp,
        min_lp,
        max_lp,
        median_lp,
        perplexity,
        rank_var,
        entropy,
        tail_entropy
    ])

# full batch feature builder
def build_feature_matrix_batch(df, model, tokenizer, batch_size=16, max_length=512):

    texts = df["text"].tolist()
    labels = df["label"].values

    features = []
    y = []

    for i in tqdm(range(0, len(texts), batch_size)):
        batch_texts = texts[i:i+batch_size]
        batch_labels = labels[i:i+batch_size]

        enc = tokenize_batch(batch_texts, tokenizer, max_length)

        input_ids = enc["input_ids"]
        attention_mask = enc["attention_mask"]

        token_log_probs, mask = get_batch_token_logprobs(
            model,
            input_ids,
            attention_mask
        )

        for j in range(len(batch_texts)):
            feat = compute_features(
                token_log_probs[j],
                mask[j]
            )
            features.append(feat)
            y.append(batch_labels[j])

    return np.vstack(features), np.array(y)

# Run on data
X_train, y_train = build_feature_matrix_batch(
    train_df,
    gpt2,
    gpt2_tokenizer,
    batch_size=16
)

X_val, y_val = build_feature_matrix_batch(
    val_df,
    gpt2,
    gpt2_tokenizer,
    batch_size=16
)

print("Train shape:", X_train.shape)
print("Val shape:", X_val.shape)

"""## 1.3 MLP 4-Class Classifier"""

# convert numpy to torch
X_train_t = torch.tensor(X_train, dtype=torch.float32)
y_train_t = torch.tensor(y_train, dtype=torch.long)

X_val_t = torch.tensor(X_val, dtype=torch.float32)
y_val_t = torch.tensor(y_val, dtype=torch.long)

train_loader = DataLoader(
    TensorDataset(X_train_t, y_train_t),
    batch_size=64,
    shuffle=True
)

val_loader = DataLoader(
    TensorDataset(X_val_t, y_val_t),
    batch_size=128,
    shuffle=False
)

# define MLP model
class MLPClassifier(nn.Module):

    def __init__(self, input_dim=10, num_classes=4):

        super().__init__()

        self.net = nn.Sequential(
            nn.Linear(input_dim, 64),
            nn.ReLU(),
            nn.Dropout(0.2),

            nn.Linear(64, 128),
            nn.ReLU(),
            nn.Dropout(0.2),

            nn.Linear(128, num_classes)
        )

    def forward(self, x):
        return self.net(x)

# initialize model
model = MLPClassifier(input_dim=10, num_classes=4).to(device)

criterion = nn.CrossEntropyLoss()
optimizer = torch.optim.Adam(model.parameters(), lr=1e-4)

# training loop
def train_one_epoch(model, loader):

    model.train()
    total_loss = 0

    for x, y in loader:

        x = x.to(device)
        y = y.to(device)

        optimizer.zero_grad()

        logits = model(x)
        loss = criterion(logits, y)

        loss.backward()
        optimizer.step()

        total_loss += loss.item()

    return total_loss / len(loader)

# evaluation
def evaluate(model, loader):
    model.eval()

    preds = []
    trues = []

    with torch.no_grad():
        for x, y in loader:
            x = x.to(device)
            logits = model(x)

            pred = torch.argmax(logits, dim=1).cpu().numpy()

            preds.extend(pred)
            trues.extend(y.numpy())

    acc = accuracy_score(trues, preds)
    f1  = f1_score(trues, preds, average="macro")

    return acc, f1

epochs = 100

for epoch in range(epochs):
    train_loss = train_one_epoch(model, train_loader)

    val_acc, val_f1 = evaluate(model, val_loader)

    print(f"Epoch {epoch+1}")
    print(f"Train Loss: {train_loss:.4f}")
    print(f"Val Acc: {val_acc:.4f} | Val F1: {val_f1:.4f}")
    print("-"*40)

"""## 1.4 Prediction on Test Data"""

def build_feature_matrix_test(df, model, tokenizer, batch_size=16, max_length=512):

    texts = df["text"].tolist()

    features = []

    for i in tqdm(range(0, len(texts), batch_size)):

        batch_texts = texts[i:i+batch_size]

        enc = tokenizer(
            batch_texts,
            return_tensors="pt",
            padding=True,
            truncation=True,
            max_length=max_length
        )

        input_ids = enc["input_ids"].to(device)
        attention_mask = enc["attention_mask"].to(device)

        with torch.no_grad():
            outputs = model(input_ids)
            logits = outputs.logits

        # shift
        shift_logits = logits[:, :-1, :]
        shift_labels = input_ids[:, 1:]
        shift_mask   = attention_mask[:, 1:]

        log_probs = F.log_softmax(shift_logits, dim=-1)

        token_log_probs = log_probs.gather(
            2,
            shift_labels.unsqueeze(-1)
        ).squeeze(-1)

        token_log_probs = token_log_probs.cpu().numpy()
        shift_mask = shift_mask.cpu().numpy()

        # per sample
        for j in range(len(batch_texts)):

            valid = token_log_probs[j][shift_mask[j] == 1]

            if len(valid) == 0:
                feat = np.zeros(10)

            else:
                # stats
                mean_lp = valid.mean()
                std_lp  = valid.std()
                min_lp  = valid.min()
                max_lp  = valid.max()
                median_lp = np.median(valid)

                perplexity = np.exp(-mean_lp)

                # logrank
                ranks = np.argsort(np.argsort(-valid))
                logrank = np.mean(np.log1p(ranks + 1))

                rank_var = np.var(ranks)

                # entropy
                probs = np.exp(valid)
                probs = probs / (np.sum(probs) + 1e-12)

                entropy = -np.sum(probs * np.log(probs + 1e-12))

                # tail entropy
                k = max(1, int(0.2 * len(valid)))
                tail_probs = np.sort(probs)[:k]
                tail_probs = tail_probs / (np.sum(tail_probs) + 1e-12)

                tail_entropy = -np.sum(tail_probs * np.log(tail_probs + 1e-12))

                feat = np.array([
                    logrank,
                    mean_lp,
                    std_lp,
                    min_lp,
                    max_lp,
                    median_lp,
                    perplexity,
                    rank_var,
                    entropy,
                    tail_entropy
                ])

            features.append(feat)

    return np.vstack(features)

X_test = build_feature_matrix_test(
    test_df,
    gpt2,
    gpt2_tokenizer,
    batch_size=16
)

# convert to tensor
X_test_t = torch.tensor(X_test, dtype=torch.float32).to(device)

# prediction function
def predict(model, X):

    model.eval()

    with torch.no_grad():
        logits = model(X)
        preds = torch.argmax(logits, dim=1)

    return preds.cpu().numpy()

test_preds = predict(model, X_test_t)

submission = pd.DataFrame({
    "ID": np.arange(len(test_preds)),
    "pred_label": test_preds
})

print(submission.head())

# save
submission.to_csv("/content/submission.csv", index=False)





