# -*- coding: utf-8 -*-
"""Exp2b.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xMcSFYK_y1i55FeHQolqu8kvFYVunOZD

# Exp2b: Distinguish Different AIs by Their Own Preference

## 2b.1 Setup
"""

!pip install -q transformers accelerate sentencepiece
!pip install -q pandas numpy tqdm scikit-learn matplotlib

!pip install -U bitsandbytes>=0.46.1

# Imports
import torch
import numpy as np
import pandas as pd

from tqdm import tqdm

from collections import Counter
from collections import defaultdict

from transformers import (
    AutoTokenizer,
    AutoModelForCausalLM
)

from sklearn.metrics import (
    accuracy_score,
    confusion_matrix,
    classification_report
)

from sklearn.model_selection import train_test_split

# Device
device = (
    "cuda"
    if torch.cuda.is_available()
    else "cpu"
)

print(device)

n_gpus = torch.cuda.device_count()
print("GPU count:", n_gpus)

"""Due to limitations in memory and computational resources, each LLM model below needs to be run separately, and the output from each run should be saved as a CSV file in the `/content` directory. In the fourth run, the large model can be omitted, and the subsequent overlap analysis and prediction can be performed directly using the saved outputs.

"""

# Load Frozen Models
# 1. GPT
gpt_tokenizer = AutoTokenizer.from_pretrained(
    "gpt2"
)
gpt_tokenizer.pad_token = gpt_tokenizer.eos_token
gpt_model = AutoModelForCausalLM.from_pretrained(
    "gpt2"
)

gpt_model.to(device)
gpt_model.eval()

# 2. Llama
llama_tokenizer = AutoTokenizer.from_pretrained(
    "TinyLlama/TinyLlama-1.1B-Chat-v1.0"
)
llama_tokenizer.pad_token = llama_tokenizer.eos_token
llama_model = AutoModelForCausalLM.from_pretrained(
    "TinyLlama/TinyLlama-1.1B-Chat-v1.0"
)

llama_model.to(device)
llama_model.eval()

# 3. Mistral
from transformers import AutoTokenizer, AutoModelForCausalLM, BitsAndBytesConfig
model_name = "mistralai/Mistral-7B-Instruct-v0.2"

# 4-bit quantization config
bnb_config = BitsAndBytesConfig(
    load_in_4bit=True,
    bnb_4bit_compute_dtype=torch.float16,
    bnb_4bit_use_double_quant=True,
    bnb_4bit_quant_type="nf4"
)

mistral_tokenizer = AutoTokenizer.from_pretrained(model_name)
mistral_tokenizer.pad_token = mistral_tokenizer.eos_token

mistral_model = AutoModelForCausalLM.from_pretrained(
    model_name,
    quantization_config=bnb_config,
    device_map="auto"
)
mistral_model.eval()

# Load Data
import pandas as pd

train_path = "/content/train_dataset.csv"
test_path  = "/content/test_dataset.csv"

train_df = pd.read_csv(train_path)
train_df, val_df = train_test_split(
    train_df,
    test_size=0.2,
    random_state=625,
    stratify=train_df["model"]
)
test_df  = pd.read_csv(test_path)

print("train shape:", train_df.shape)
print("val shape:", val_df.shape)
print("test shape:", test_df.shape)

print(train_df.head(8))

train_df["text"] = train_df["text"].astype(str)
val_df["text"] = val_df["text"].astype(str)
test_df["text"]  = test_df["text"].astype(str)

train_df["model"] = train_df["model"].astype(str).str.lower().str.strip()
train_df["domain"] = train_df["domain"].astype(str).str.lower().str.strip()
val_df["model"] = val_df["model"].astype(str).str.lower().str.strip()
val_df["domain"] = val_df["domain"].astype(str).str.lower().str.strip()

# Split train dataset by different models
gpt_texts = train_df[train_df["model"].str.contains("gpt")]["text"].tolist()

llama_texts = train_df[train_df["model"].str.contains("llama")]["text"].tolist()

mistral_texts = train_df[
    train_df["model"].str.contains("mistral")
]["text"].tolist()

"""## 1b.2 Observed Counts and Expected Counts"""

# Observed Counts
def observed_counts(
    texts,
    tokenizer
):

    counter = Counter()

    for text in tqdm(texts):

        ids = tokenizer.encode(
            text,
            truncation=True,
            max_length=1024
        )

        counter.update(ids)

    return counter

# Expected Counts
def expected_counts(
    texts,
    model,
    tokenizer,
    device=device,
    batch_size=8,       # use batch to accelerate
    top_k=30,
    max_length=512
):

    expected = defaultdict(float)

    model.eval()

    for i in tqdm(range(0, len(texts), batch_size)):

        batch_texts = texts[i:i+batch_size]

        inputs = tokenizer(
            batch_texts,
            return_tensors="pt",
            padding=True,
            truncation=True,
            max_length=max_length
        )

        inputs = {k: v.to(device) for k, v in inputs.items()}

        with torch.no_grad():

            outputs = model(**inputs)
            logits = outputs.logits

            probs = torch.softmax(logits, dim=-1)

        # probs: [B, T, V]
        batch_size_actual = probs.shape[0]

        for b in range(batch_size_actual):

            seq_len = inputs["attention_mask"][b].sum().item()

            for t in range(seq_len - 1):

                top_p, top_idx = torch.topk(
                    probs[b, t],
                    k=top_k
                )

                top_p = top_p.cpu()
                top_idx = top_idx.cpu()

                for p, idx in zip(top_p, top_idx):

                    expected[int(idx)] += float(p)

    return expected

"""## 1b.3 Comparison Within Each 2 Models
$$
z_i^{j,k} = \frac{N_i^{j}-E_i^{k}}{\sqrt{E_i^{k}}},
$$
where $N_i^{j}$ denotes the actual frequency of token $i$ in text generated by $j$, and $E_i^k$ denotes the expected frequency of token $i$ genereated by $k$. From our assumption, this indicator can capture "greenlist" of different models.
"""

# Using z-scores
def recover_greenlist(
    texts,
    model,
    tokenizer,
    device=device,
    batch_size=8,
    top_k=30,
    max_length=512
):

    obs = observed_counts(
        texts,
        tokenizer
    )

    exp = expected_counts(
        texts,
        model,
        tokenizer
    )

    rows = []

    all_tokens = (
        set(obs.keys())
        |
        set(exp.keys())
    )

    for tid in all_tokens:

        N = obs.get(tid,0)

        E = exp.get(tid,0)

        if E < 30:
            continue

        z = (
            N-E
        ) / np.sqrt(E)

        token_str = (
            tokenizer.decode(
                [tid],
                clean_up_tokenization_spaces=True
            )
            .lower()
            .strip()
        )

        rows.append(
            [
                tid,
                token_str,
                N,
                E,
                z
            ]
        )

    df = pd.DataFrame(
        rows,
        columns=[
            "token_id",
            "token",
            "N",
            "E",
            "z"
        ]
    )

    df = df.sort_values(
        "z",
        ascending=False
    )

    return df.head(top_k)

"""Comparison within each 2 models:
- gpt vs mistral
- llama vs gpt
- mistral vs llama
"""

# Recover 3 Candidate Greenlists
gpt_green_df = recover_greenlist(
    gpt_texts,
    mistral_model,
    mistral_tokenizer,
)

# Save Top-K Tokens
gpt_green_df.to_csv(
    "/content/gpt_green_tokens.csv",
    index=False
)

# operate seperately, or out of memory
llama_green_df = recover_greenlist(
    llama_texts,
    gpt_model,
    gpt_tokenizer,
)

llama_green_df.to_csv(
    "/content/llama_green_tokens.csv",
    index=False
)

mistral_green_df = recover_greenlist(
    mistral_texts,
    llama_model,
    llama_tokenizer,
)

mistral_green_df.to_csv(
    "/content/mistral_green_tokens.csv",
    index=False
)

"""## 1b.4 Overlap Analysis"""

gpt_green_df = pd.read_csv("/content/gpt_green_tokens.csv")
llama_green_df = pd.read_csv("/content/llama_green_tokens.csv")
mistral_green_df = pd.read_csv("/content/mistral_green_tokens.csv")

gpt_set = set(
    gpt_green_df["token"]
)

llama_set = set(
    llama_green_df["token"]
)

mistral_set = set(
    mistral_green_df["token"]
)

def jaccard(A,B):

    return (
        len(A&B)
        /
        len(A|B)
    )

print(
    "GPT-Llama",
    jaccard(
        gpt_set,
        llama_set
    )
)

print(
    "GPT-Mistral",
    jaccard(
        gpt_set,
        mistral_set
    )
)

print(
    "Llama-Mistral",
    jaccard(
        llama_set,
        mistral_set
    )
)

"""## 1b.5 Calculate a Score to Evaluate"""

# Weighted Greenlist Dictionary
gpt_dict = dict(
    zip(
        gpt_green_df.token,
        gpt_green_df.z
    )
)

llama_dict = dict(
    zip(
        llama_green_df.token,
        llama_green_df.z
    )
)

mistral_dict = dict(
    zip(
        mistral_green_df.token,
        mistral_green_df.z
    )
)

# Score
def weighted_score(text, green_dict):

    score = 0

    for token, z in green_dict.items():

        if token is None:
            continue

        token = str(token)

        if token == "nan" or token == "None":
            continue

        if not isinstance(z, (int, float)):
            continue

        score += text.count(token) * float(z)

    return score

# Multi-class Score
def predict_model(
    text
):

    s_gpt = weighted_score(
        text,
        gpt_dict
    )

    s_llama = weighted_score(
        text,
        llama_dict
    )

    s_mistral = weighted_score(
        text,
        mistral_dict
    )

    scores = [
        s_gpt,
        s_llama,
        s_mistral
    ]

    return (
        np.argmax(scores)
        + 1
    )

# Evaluation on val_dataset
preds_val = []

for text in val_df["text"]:

    preds_val.append(
        predict_model(text)
    )

# Accuracy
acc_val = accuracy_score(
    val_df["label"],
    preds_val
)

print(
    "Accuracy:",
    acc_val
)

# Other indicators
print(
    classification_report(
        val_df["label"],
        preds_val
    )
)

"""## 1b.6 Combination of Exp 1a and Exp 1b"""

sub = pd.read_csv("/content/detectgpt_prediction_10.csv")  #/content/submission_exp2a.csv

# pred_label == 1
ids = sub.loc[sub["pred_label"] == 1, "ID"].values
test_df = test_df.reset_index(drop=True)
selected_texts = test_df.iloc[ids]["text"]

preds_test_ai = []
for text in selected_texts:
    preds_test_ai.append(predict_model(text))

print(len(ids))
print(len(preds_test_ai))

sub.loc[sub["ID"].isin(ids), "pred_label"] = preds_test_ai
sub.to_csv("/content/submission_exp2ab.csv", index=False)







