# -*- coding: utf-8 -*-
"""Exp2a.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11_NeK64NKXo7p75ysbPQmtW0LBiI6jDZ

# Exp2a:

## 2a.1 Setup
"""

!pip install -q transformers accelerate sentencepiece scikit-learn tqdm

import random
import re
import torch
import torch.nn.functional as F
import numpy as np
import pandas as pd
from tqdm import tqdm
from sklearn.model_selection import train_test_split
from sklearn.metrics import (
    roc_curve,
    accuracy_score,
    f1_score,
    roc_auc_score,
    precision_score,
    recall_score,
    classification_report,
)

device = "cuda" if torch.cuda.is_available() else "cpu"
print("Device:", device)

# Load Data
train_df = pd.read_csv("/content/train_dataset.csv")  # train_attack_data
test_df = pd.read_csv("/content/test_dataset.csv")

print(train_df.head())
print(test_df.head())

train_df["text"] = train_df["text"].astype(str)
test_df["text"]  = test_df["text"].astype(str)

train_df["model"] = train_df["model"].astype(str).str.lower().str.strip()
train_df["domain"] = train_df["domain"].astype(str).str.lower().str.strip()

print(train_df.loc[7624, "text"])
print(type(train_df.loc[7624, "text"]))
print(train_df.loc[7834, "text"])
print(type(train_df.loc[7834, "text"]))

train_df = train_df.drop(index=7624)
train_df = train_df.drop(index=7834)

def is_bad(x):
    if x is None:
        return True

    if isinstance(x, float) and np.isnan(x):
        return True

    s = str(x).strip().lower()

    if s == "" or s == "nan":
        return True

    return False


train_df = train_df[~train_df["text"].apply(is_bad)]

train_df, val_df = train_test_split(
    train_df,
    test_size=0.2,
    random_state=625,
    stratify=train_df["model"]
)

print("train shape:", train_df.shape)
print("val shape:", val_df.shape)
print("test shape:", test_df.shape)

print(train_df.head(8))

# binary  category
def binarize_label(x):
    # AI = 1, Human = 0
    if x in [1, 2, 3]:
        return 1
    else:
        return 0

train_df["label"] = train_df["label"].apply(binarize_label)
val_df["label"]   = val_df["label"].apply(binarize_label)

# Load Models
# 1.GPT-2 Scorer (more stable with float32)
from transformers import AutoTokenizer, AutoModelForCausalLM, AutoModelForSeq2SeqLM

gpt2_name = "gpt2"

gpt2 = AutoModelForCausalLM.from_pretrained(
    gpt2_name,
    torch_dtype=torch.float32
).to(device)

gpt2.eval()

gpt2_tokenizer = AutoTokenizer.from_pretrained(gpt2_name)

gpt2_tokenizer.pad_token = gpt2_tokenizer.eos_token

# 2.T5-Base Perturbation Model
t5_name = "t5-small"

t5 = AutoModelForSeq2SeqLM.from_pretrained(
    t5_name,
    torch_dtype=torch.float32
).to(device)

t5.eval()

t5_tokenizer = AutoTokenizer.from_pretrained(t5_name)





"""## 2a.2 Span Marking and T5 Perturbation"""

# Span Masking
def mask_text(text,
              mask_ratio=0.15,
              mean_span_length=3):

    # T5 sentencepiece tokens
    text = t5_tokenizer.decode(
    t5_tokenizer(
        text,
        truncation=True,
        max_length=512
    )["input_ids"],
    skip_special_tokens=True
)
    tokens = t5_tokenizer.tokenize(text)

    n_tokens = len(tokens)

    if n_tokens == 0:
        return text

    target_mask = max(1, int(mask_ratio * n_tokens))

    masked_tokens = []

    num_masked = 0
    sentinel_id = 0

    i = 0

    while i < n_tokens:
        if num_masked >= target_mask:
            masked_tokens.extend(tokens[i:])
            break

        if random.random() < mask_ratio:

            span_len = max(
                1,
                int(random.expovariate(1 / mean_span_length))
            )

            span_len = min(
                span_len,
                target_mask - num_masked,
                n_tokens - i
            )

            masked_tokens.append(f"<extra_id_{sentinel_id}>")

            sentinel_id += 1

            i += span_len
            num_masked += span_len

        else:

            masked_tokens.append(tokens[i])
            i += 1

    masked_text = t5_tokenizer.convert_tokens_to_string(masked_tokens)

    return masked_text

# Recover spans using T5
def fill_masks(masked_text):

    inputs = t5_tokenizer(
        masked_text,
        return_tensors="pt",
        truncation=True,
        max_length=1024
    ).to(device)

    with torch.no_grad():

        outputs = t5.generate(
            **inputs,
            do_sample=True,
            top_p=0.95,
            temperature=1.0,
            max_new_tokens=96
        )

    generated = t5_tokenizer.decode(
        outputs[0],
        skip_special_tokens=False
    )

    return generated

# Replace <extra_id_i> with generated spans
def apply_fills(masked_text, generated_text):

    # split by sentinels
    fills = re.split(r"<extra_id_\d+>", generated_text)

    # remove first empty element
    fills = fills[1:]

    result = masked_text

    for i, fill in enumerate(fills):

        fill = fill.replace("</s>", "").strip()

        result = result.replace(
            f"<extra_id_{i}>",
            fill,
            1
        )

    # remove remaining sentinels if any
    result = re.sub(r"<extra_id_\d+>", "", result)

    result = re.sub(r"\s+", " ", result).strip()

    return result

# Generate batch T5 perturbations
def t5_perturb(text,
               num_perturb=10):

    masked_texts = [
        mask_text(text)
        for _ in range(num_perturb)
    ]

    inputs = t5_tokenizer(
        masked_texts,
        padding=True,
        truncation=True,
        max_length=1024,
        return_tensors="pt"
    ).to(device)

    with torch.no_grad():
        outputs = t5.generate(
            **inputs,
            do_sample=True,
            top_p=0.95,
            temperature=1.0,
            max_new_tokens=96
        )

    generated = t5_tokenizer.batch_decode(
        outputs,
        skip_special_tokens=False
    )

    perturbations = []
    for masked, gen in zip(masked_texts, generated):

        perturbations.append(
            apply_fills(masked, gen)
        )

    return perturbations

"""## 2a.3 GPT2 Log Probability and DetectGPT Score"""

# Batch GPT2 Sequence Log Probability
def gpt2_logprob(text):

    if text is None or str(text).strip() == "":
        return -1e9   # extreme low scores，i.e. randomly pick human or ai

    inputs = gpt2_tokenizer(
        text,
        padding=True,
        truncation=True,
        max_length=1024,
        return_tensors="pt"
    ).to(device)

    input_ids = inputs["input_ids"]
    attention_mask = inputs["attention_mask"]

    with torch.no_grad():
        outputs = gpt2(
            input_ids=input_ids,
            attention_mask=attention_mask
            )
        logits = outputs.logits

    # shift
    shift_logits = logits[:, :-1]
    shift_labels = input_ids[:, 1:]
    shift_mask = attention_mask[:, 1:]

    # token log probabilities
    log_probs = F.log_softmax(
        shift_logits,
        dim=-1
    )

    token_log_probs = log_probs.gather(
        dim=-1,
        index=shift_labels.unsqueeze(-1)
    ).squeeze(-1)

    token_log_probs = token_log_probs * shift_mask
    seq_log_probs = token_log_probs.sum(dim=1)

    return seq_log_probs.cpu().numpy()

# DectGPT Score
def detectgpt_score(
        text,
        num_perturb=10):

    # original
    orig_logprob = gpt2_logprob(text)

    # perturbations
    perturbed = t5_perturb(
        text,
        num_perturb=num_perturb
    )

    # perturbation scores
    pert_scores = gpt2_logprob(
        perturbed
    )

    # DetectGPT score: (orig - μ)/σ
    mu = pert_scores.mean()
    sigma = pert_scores.std()

    if sigma < 1e-6:
        sigma = 1e-6
    score = (orig_logprob - mu) / sigma

    return score

"""## 2a.4 Evaluation"""

# Score Dataset
def score_dataset(
    texts,
    num_perturb=10,
):

    scores = []

    for text in tqdm(
        texts,
        total=len(texts),
        desc="Scoring"
    ):

        score = detectgpt_score(
            text,
            num_perturb=num_perturb
        )
        scores.append(score)

    return np.asarray(scores)

# Threshold Selection
def select_threshold(
    scores,
    labels,
    max_fpr=0.045
):

    fpr, tpr, thresholds = roc_curve(
        labels,
        scores
    )

    valid = np.where(
        fpr <= max_fpr
    )[0]

    if len(valid) == 0:
        best = np.argmax(tpr)
    else:
        best = valid[
            np.argmax(tpr[valid])
        ]

    threshold = thresholds[best]

    print(f"Threshold : {threshold:.4f}")
    print(f"FPR       : {fpr[best]:.4f}")
    print(f"TPR       : {tpr[best]:.4f}")

    return threshold

# Evaluation
def evaluate(
    scores,
    labels,
    threshold,
):

    preds = (
        scores > threshold
    ).astype(int)

    print(
        "Accuracy :",
        accuracy_score(
            labels,
            preds
        )
    )
    print(
        "Precision:",
        precision_score(
            labels,
            preds
        )
    )
    print(
        "Recall   :",
        recall_score(
            labels,
            preds
        )
    )
    print(
        "F1 Score :",
        f1_score(
            labels,
            preds
        )
    )
    print(
        "ROC AUC  :",
        roc_auc_score(
            labels,
            scores
        )
    )

    print("\nClassification Report\n")
    print(
        classification_report(
            labels,
            preds,
            digits=4
        )
    )

    return preds

# Predict Val/Test Set
def predict(
    scores,
    threshold,
):

    preds = (
        scores > threshold
    ).astype(int)

    return preds

# Save CSV
def save_submission(
    preds,
    filename="detectgpt_prediction.csv"
):

    save_path = f"/content/{filename}"
    preds = np.array(preds).squeeze()

    submission = pd.DataFrame({
        "ID": np.arange(
            len(preds)
        ),
        "pred_label": preds
    })

    submission.to_csv(
        save_path,
        index=False
    )

    print(
        f"Prediction saved to {save_path}"
    )

    return submission

# Use functions to evaluate
train_scores = score_dataset(train_df["text"])

print(train_scores)

train_scores = np.array(train_scores).squeeze()

pd.DataFrame({
    "score": train_scores
}).to_csv("/content/train_scores.csv", index=True)

threshold = select_threshold(
    train_scores,
    train_df["label"]
)
print(threshold)

val_scores = score_dataset(val_df["text"])
val_pred = evaluate(
    val_scores,
    val_df["label"],
    threshold
)

test_scores = score_dataset(test_df["text"])
test_pred = predict(
    test_scores,
    threshold
)

save_submission(
    test_pred,
    filename="detectgpt_prediction.csv"
)

# Reasons
import matplotlib.pyplot as plt

scores = np.array(train_scores).squeeze()

labels = train_df["label"].values

ai_scores = scores[labels == 1]
human_scores = scores[labels == 0]

plt.hist(human_scores, alpha=0.5, label="Human", bins=50)
plt.hist(ai_scores, alpha=0.5, label="AI", bins=50)

plt.legend()
plt.title("Score Distribution: AI vs Human")
plt.show()